CREATE TABLE olimpic_ita_medals (pkid INTEGER PRIMARY KEY AUTOINCREMENT, year INT, city TEXT, sport TEXT, gender TEXT, golds, silvers, bronzes);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (78, 1960, 'rome', 'aquatics', 'Men', 12, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (79, 1960, 'rome', 'athletics', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (80, 1960, 'rome', 'athletics', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (81, 1960, 'rome', 'boxing', 'Men', 3, 3, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (82, 1960, 'rome', 'canoe / kayak', 'Men', 0, 2, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (83, 1960, 'rome', 'cycling', 'Men', 12, 1, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (84, 1960, 'rome', 'equestrian', 'Men', 1, 1, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (85, 1960, 'rome', 'fencing', 'Men', 7, 5, 6);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (86, 1960, 'rome', 'fencing', 'Women', 0, 0, 5);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (87, 1960, 'rome', 'gymnastics', 'Men', 0, 1, 7);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (88, 1960, 'rome', 'rowing', 'Men', 0, 4, 5);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (89, 1960, 'rome', 'sailing', 'Men', 0, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (90, 1960, 'rome', 'shooting', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (91, 1960, 'rome', 'weightlifting', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (92, 1964, 'tokyo', 'aquatics', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (93, 1964, 'tokyo', 'athletics', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (94, 1964, 'tokyo', 'boxing', 'Men', 2, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (95, 1964, 'tokyo', 'cycling', 'Men', 4, 11, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (96, 1964, 'tokyo', 'equestrian', 'Men', 4, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (97, 1964, 'tokyo', 'fencing', 'Men', 0, 10, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (98, 1964, 'tokyo', 'fencing', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (99, 1964, 'tokyo', 'gymnastics', 'Men', 1, 1, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (100, 1964, 'tokyo', 'rowing', 'Men', 0, 5, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (101, 1964, 'tokyo', 'shooting', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (102, 1968, 'mexico', 'aquatics', 'Men', 1, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (103, 1968, 'mexico', 'athletics', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (104, 1968, 'mexico', 'boxing', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (105, 1968, 'mexico', 'cycling', 'Men', 1, 1, 8);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (106, 1968, 'mexico', 'fencing', 'Men', 0, 5, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (107, 1968, 'mexico', 'rowing', 'Men', 3, 0, 4);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (108, 1968, 'mexico', 'sailing', 'Men', 0, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (109, 1968, 'mexico', 'shooting', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (110, 1972, 'munich', 'aquatics', 'Men', 1, 1, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (111, 1972, 'munich', 'aquatics', 'Women', 0, 1, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (112, 1972, 'munich', 'athletics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (113, 1972, 'munich', 'athletics', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (114, 1972, 'munich', 'equestrian', 'Men', 1, 1, 4);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (115, 1972, 'munich', 'fencing', 'Men', 5, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (116, 1972, 'munich', 'fencing', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (117, 1972, 'munich', 'shooting', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (118, 1972, 'munich', 'weightlifting', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (119, 1972, 'munich', 'wrestling', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (120, 1976, 'montreal', 'aquatics', 'Men', 1, 12, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (121, 1976, 'montreal', 'archery', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (122, 1976, 'montreal', 'athletics', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (123, 1976, 'montreal', 'cycling', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (124, 1976, 'montreal', 'fencing', 'Men', 1, 10, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (125, 1976, 'montreal', 'fencing', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (126, 1976, 'montreal', 'judo', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (127, 1976, 'montreal', 'shooting', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (128, 1980, 'moscow', 'aquatics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (129, 1980, 'moscow', 'archery', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (130, 1980, 'moscow', 'athletics', 'Men', 2, 0, 4);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (131, 1980, 'moscow', 'athletics', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (132, 1980, 'moscow', 'basketball', 'Men', 0, 12, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (133, 1980, 'moscow', 'boxing', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (134, 1980, 'moscow', 'equestrian', 'Men', 1, 2, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (135, 1980, 'moscow', 'equestrian', 'Women', 0, 2, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (136, 1980, 'moscow', 'fencing', 'Men', 0, 5, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (137, 1980, 'moscow', 'judo', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (138, 1980, 'moscow', 'sailing', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (139, 1980, 'moscow', 'shooting', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (140, 1980, 'moscow', 'wrestling', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (141, 1984, 'los angeles', 'athletics', 'Men', 2, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (142, 1984, 'los angeles', 'athletics', 'Women', 1, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (143, 1984, 'los angeles', 'boxing', 'Men', 1, 2, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (144, 1984, 'los angeles', 'cycling', 'Men', 4, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (145, 1984, 'los angeles', 'fencing', 'Men', 11, 1, 6);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (146, 1984, 'los angeles', 'fencing', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (147, 1984, 'los angeles', 'judo', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (148, 1984, 'los angeles', 'modern pentathlon', 'Men', 4, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (149, 1984, 'los angeles', 'rowing', 'Men', 3, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (150, 1984, 'los angeles', 'sailing', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (151, 1984, 'los angeles', 'shooting', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (152, 1984, 'los angeles', 'shooting', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (153, 1984, 'los angeles', 'volleyball', 'Men', 0, 0, 12);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (154, 1984, 'los angeles', 'weightlifting', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (155, 1984, 'los angeles', 'wrestling', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (156, 1988, 'seoul', 'aquatics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (157, 1988, 'seoul', 'athletics', 'Men', 1, 1, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (158, 1988, 'seoul', 'boxing', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (159, 1988, 'seoul', 'fencing', 'Men', 1, 0, 6);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (160, 1988, 'seoul', 'fencing', 'Women', 0, 5, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (161, 1988, 'seoul', 'modern pentathlon', 'Men', 0, 4, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (162, 1988, 'seoul', 'rowing', 'Men', 7, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (163, 1988, 'seoul', 'wrestling', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (164, 1992, 'barcelona', 'aquatics', 'Men', 13, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (165, 1992, 'barcelona', 'athletics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (166, 1992, 'barcelona', 'canoe / kayak', 'Men', 1, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (167, 1992, 'barcelona', 'cycling', 'Men', 2, 4, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (168, 1992, 'barcelona', 'fencing', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (169, 1992, 'barcelona', 'fencing', 'Women', 6, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (170, 1992, 'barcelona', 'judo', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (171, 1992, 'barcelona', 'modern pentathlon', 'Men', 0, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (172, 1992, 'barcelona', 'rowing', 'Men', 0, 3, 4);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (173, 1992, 'barcelona', 'shooting', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (174, 1992, 'barcelona', 'wrestling', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (175, 1996, 'atlanta', 'aquatics', 'Men', 0, 0, 14);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (176, 1996, 'atlanta', 'archery', 'Men', 0, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (177, 1996, 'atlanta', 'athletics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (178, 1996, 'atlanta', 'athletics', 'Women', 0, 2, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (179, 1996, 'atlanta', 'canoe / kayak', 'Men', 3, 3, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (180, 1996, 'atlanta', 'canoe / kayak', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (181, 1996, 'atlanta', 'cycling', 'Men', 2, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (182, 1996, 'atlanta', 'cycling', 'Women', 2, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (183, 1996, 'atlanta', 'fencing', 'Men', 4, 0, 3);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (184, 1996, 'atlanta', 'fencing', 'Women', 3, 4, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (185, 1996, 'atlanta', 'gymnastics', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (186, 1996, 'atlanta', 'judo', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (187, 1996, 'atlanta', 'judo', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (188, 1996, 'atlanta', 'rowing', 'Men', 2, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (189, 1996, 'atlanta', 'sailing', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (190, 1996, 'atlanta', 'shooting', 'Men', 2, 1, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (191, 1996, 'atlanta', 'volleyball', 'Men', 0, 12, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (192, 2000, 'sydney', 'aquatics', 'Men', 3, 1, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (193, 2000, 'sydney', 'archery', 'Men', 0, 3, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (194, 2000, 'sydney', 'athletics', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (195, 2000, 'sydney', 'athletics', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (196, 2000, 'sydney', 'boxing', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (197, 2000, 'sydney', 'canoe / kayak', 'Men', 2, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (198, 2000, 'sydney', 'canoe / kayak', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (199, 2000, 'sydney', 'cycling', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (200, 2000, 'sydney', 'cycling', 'Women', 2, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (201, 2000, 'sydney', 'fencing', 'Men', 4, 0, 4);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (202, 2000, 'sydney', 'fencing', 'Women', 4, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (203, 2000, 'sydney', 'judo', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (204, 2000, 'sydney', 'judo', 'Women', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (205, 2000, 'sydney', 'rowing', 'Men', 4, 6, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (206, 2000, 'sydney', 'sailing', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (207, 2000, 'sydney', 'sailing', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (208, 2000, 'sydney', 'shooting', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (209, 2000, 'sydney', 'shooting', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (210, 2000, 'sydney', 'volleyball', 'Men', 0, 0, 12);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (211, 2004, 'athens', 'aquatics', 'Men', 0, 0, 6);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (212, 2004, 'athens', 'aquatics', 'Women', 13, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (213, 2004, 'athens', 'archery', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (214, 2004, 'athens', 'athletics', 'Men', 2, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (215, 2004, 'athens', 'basketball', 'Men', 0, 11, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (216, 2004, 'athens', 'boxing', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (217, 2004, 'athens', 'canoe / kayak', 'Men', 0, 2, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (218, 2004, 'athens', 'canoe / kayak', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (219, 2004, 'athens', 'cycling', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (220, 2004, 'athens', 'fencing', 'Men', 4, 4, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (221, 2004, 'athens', 'fencing', 'Women', 1, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (222, 2004, 'athens', 'football', 'Men', 0, 0, 17);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (223, 2004, 'athens', 'gymnastics', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (224, 2004, 'athens', 'gymnastics', 'Women', 0, 6, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (225, 2004, 'athens', 'judo', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (226, 2004, 'athens', 'rowing', 'Men', 0, 0, 10);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (227, 2004, 'athens', 'sailing', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (228, 2004, 'athens', 'shooting', 'Men', 1, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (229, 2004, 'athens', 'shooting', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (230, 2004, 'athens', 'volleyball', 'Men', 0, 11, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (231, 2008, 'beijing', 'aquatics', 'Women', 1, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (232, 2008, 'beijing', 'archery', 'Men', 0, 3, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (233, 2008, 'beijing', 'athletics', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (234, 2008, 'beijing', 'athletics', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (235, 2008, 'beijing', 'boxing', 'Men', 1, 1, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (236, 2008, 'beijing', 'canoe / kayak', 'Men', 0, 0, 2);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (237, 2008, 'beijing', 'canoe / kayak', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (238, 2008, 'beijing', 'cycling', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (239, 2008, 'beijing', 'fencing', 'Men', 1, 0, 9);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (240, 2008, 'beijing', 'fencing', 'Women', 1, 0, 5);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (241, 2008, 'beijing', 'judo', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (242, 2008, 'beijing', 'rowing', 'Men', 0, 4, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (243, 2008, 'beijing', 'sailing', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (244, 2008, 'beijing', 'sailing', 'Women', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (245, 2008, 'beijing', 'shooting', 'Men', 0, 2, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (246, 2008, 'beijing', 'shooting', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (247, 2008, 'beijing', 'taekwondo', 'Men', 0, 1, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (248, 2008, 'beijing', 'wrestling', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (249, 2012, 'london', 'aquatics', 'Men', 0, 13, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (250, 2012, 'london', 'aquatics', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (251, 2012, 'london', 'archery', 'Men', 3, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (252, 2012, 'london', 'athletics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (253, 2012, 'london', 'boxing', 'Men', 0, 2, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (254, 2012, 'london', 'canoe', 'Men', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (255, 2012, 'london', 'cycling', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (256, 2012, 'london', 'fencing', 'Men', 4, 1, 4);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (257, 2012, 'london', 'fencing', 'Women', 5, 1, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (258, 2012, 'london', 'gymnastics', 'Men', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (259, 2012, 'london', 'gymnastics', 'Women', 0, 0, 6);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (260, 2012, 'london', 'judo', 'Women', 0, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (261, 2012, 'london', 'rowing', 'Men', 0, 2, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (262, 2012, 'london', 'shooting', 'Men', 1, 3, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (263, 2012, 'london', 'shooting', 'Women', 1, 0, 0);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (264, 2012, 'london', 'taekwondo', 'Men', 1, 0, 1);
INSERT INTO olimpic_ita_medals (pkid, year, city, sport, gender, golds, silvers, bronzes) VALUES (265, 2012, 'london', 'volleyball', 'Men', 0, 0, 12);
CREATE INDEX gender_ix ON olimpic_ita_medals (gender);
